export const FETCH_PACKAGES = 'fetchPackages'
export const SET_SPINNER_STATE = 'setSpinnerState'
export const SET_ERROR_STATE = 'setErrorState'
export const SET_DIALOG_STATE = 'setDialogState'
export const SET_PACKAGE_INFO = 'setPackagesInfo'
export const SET_PACKAGES = 'setPackages'
